# Generated by Django 5.2.5 on 2025-08-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('government', 'Government'), ('ngo', 'NGO'), ('company', 'Private Company'), ('personal', 'Personal'), ('bodaboda', 'Bodaboda')], max_length=20, null=True),
        ),
    ]
